version: '3.8'
volumes:
  postgres_data:
  staticfiles:
services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env
  web:
    image: udinilya/yatube_web:v3
    restart: always
    command: gunicorn yatube.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - staticfiles:/code/static
    depends_on:
      - db
    env_file:
      - ./.env
  migration:
    image: udinilya/yatube_web:v3
    command: python3 manage.py migrate --noinput
    depends_on:
      - web
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.6
    volumes:
      - staticfiles:/static
      - ./host.conf:/etc/nginx/conf.d
    ports:
      - 8888:80
    depends_on:
      - web
